version: '3'
services:
#  prometheus:
#    image: prom/prometheus
#    ports:
#      - "9090:9090"
#    volumes:
#      - ./prometheus:/etc/prometheus
#    command:
#      - "--config.file=/etc/prometheus/prometheus.yml"

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - "dbdata:/var/lib/postgresql/data"

  web:
    build: .
    env_file: .env
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    volumes:
      - .:/app
volumes:
  dbdata:
#  prometheus: